### ISSUE TITLE
undefined method `gsub' for nil:NilClass

### ISSUE THREAD

**Issue by pokeswap** [Arachni/arachni-ui-web#113]
Whenever I attempt to view a scan or profile, or create a new profile, I receive the following error: 

undefined method `gsub' for nil:NilClass

 Showing /usr/share/arachni/ui/arachni-ui-web/app/views/issues/_group_row.html.erb where line #34 raised:

undefined method `gsub' for nil:NilClass

Extracted source (around line #62):

60
61
62
63
64
65
              

	

        return '' if string.empty?

        html = Kramdown::Document.new( string.recode ).to_html
        Loofah.fragment( html ).scrub!(:prune).to_s.html_safe
    end

Trace of template inclusion: app/views/issues/_table.html.erb, app/views/scans/show.html.erb

Rails.root: /usr/share/arachni/ui/arachni-ui-web

Here is a link to the full traceback: http://paste.ubuntu.com/23134115/

**Comment by pokeswap** [comment]
framework trace: http://paste.ubuntu.com/23134117/

application trace:


app/helpers/application_helper.rb:62:in `m'
app/views/issues/_group_row.html.erb:34:in `_app_views_issues__group_row_html_erb__1531891142710166503_57738840'
app/views/issues/_table.html.erb:69:in `block in _app_views_issues__table_html_erb___1433190237702865565_35002620'
app/views/issues/_table.html.erb:68:in `each'
app/views/issues/_table.html.erb:68:in `_app_views_issues__table_html_erb___1433190237702865565_35002620'
app/views/scans/show.html.erb:80:in `_app_views_scans_show_html_erb__1887572410669784447_53618800'
app/controllers/scans_controller.rb:80:in `show'

session and env dump: http://paste.ubuntu.com/23134118/

by the way, if it helps, this is a fresh installation.

**Comment by Zapotek** [comment]
You don't seem to be using the self-contained packages, are you running it from source?
