### ISSUE TITLE
Login page and Sign in problem

### ISSUE THREAD

**Issue by Comancheroo** [Arachni/arachni-ui-web#23]
Hello,
localhost:4567 Login page does not work because continuously refreshes the page.
And where is email and password for sign in?

Thanks.

**Comment by RealOrko** [comment]
Hi

I just tried this on fedora 31 and noticed the default logins do not work. I tried: 

```
    Administrator:
        E-mail address: admin@admin.admin
        Password:       administrator

    User:
        E-mail address: user@user.user
        Password:       regular_user
```

Also when I try to run the `./arachni_web_create_user gavin@local.com password Gavin` I get the following error trace output: 

```
./arachni_web_create_user gavin@cryosharp.com password Gavin
/home/gavin/Downloads/arachni-1.5.1-0.5.12-linux-x86_64/arachni-1.5.1-0.5.12/system/gems/gems/bcrypt-3.1.11/lib/bcrypt/password.rb:60:in `initialize': invalid hash (BCrypt::Errors::InvalidHash)
	from /home/gavin/Downloads/arachni-1.5.1-0.5.12-linux-x86_64/arachni-1.5.1-0.5.12/system/gems/gems/bcrypt-3.1.11/lib/bcrypt/password.rb:46:in `new'
	from /home/gavin/Downloads/arachni-1.5.1-0.5.12-linux-x86_64/arachni-1.5.1-0.5.12/system/gems/gems/bcrypt-3.1.11/lib/bcrypt/password.rb:46:in `create'
	from /home/gavin/Downloads/arachni-1.5.1-0.5.12-linux-x86_64/arachni-1.5.1-0.5.12/system/gems/gems/devise-3.5.10/lib/devise/encryptor.rb:9:in `digest'
	from /home/gavin/Downloads/arachni-1.5.1-0.5.12-linux-x86_64/arachni-1.5.1-0.5.12/system/gems/gems/devise-3.5.10/lib/devise/models/database_authenticatable.rb:150:in `password_digest'
	from /home/gavin/Downloads/arachni-1.5.1-0.5.12-linux-x86_64/arachni-1.5.1-0.5.12/system/gems/gems/devise-3.5.10/lib/devise/models/database_authenticatable.rb:43:in `password='
	from /home/gavin/Downloads/arachni-1.5.1-0.5.12-linux-x86_64/arachni-1.5.1-0.5.12/system/gems/gems/activerecord-4.2.5.1/lib/active_record/attribute_assignment.rb:54:in `public_send'
	from /home/gavin/Downloads/arachni-1.5.1-0.5.12-linux-x86_64/arachni-1.5.1-0.5.12/system/gems/gems/activerecord-4.2.5.1/lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
	from /home/gavin/Downloads/arachni-1.5.1-0.5.12-linux-x86_64/arachni-1.5.1-0.5.12/system/gems/gems/activerecord-4.2.5.1/lib/active_record/attribute_assignment.rb:41:in `block in assign_attributes'
	from /home/gavin/Downloads/arachni-1.5.1-0.5.12-linux-x86_64/arachni-1.5.1-0.5.12/system/gems/gems/activerecord-4.2.5.1/lib/active_record/attribute_assignment.rb:35:in `each'
	from /home/gavin/Downloads/arachni-1.5.1-0.5.12-linux-x86_64/arachni-1.5.1-0.5.12/system/gems/gems/activerecord-4.2.5.1/lib/active_record/attribute_assignment.rb:35:in `assign_attributes'
	from /home/gavin/Downloads/arachni-1.5.1-0.5.12-linux-x86_64/arachni-1.5.1-0.5.12/system/gems/gems/activerecord-4.2.5.1/lib/active_record/core.rb:566:in `init_attributes'
	from /home/gavin/Downloads/arachni-1.5.1-0.5.12-linux-x86_64/arachni-1.5.1-0.5.12/system/gems/gems/activerecord-4.2.5.1/lib/active_record/core.rb:281:in `initialize'
	from /home/gavin/Downloads/arachni-1.5.1-0.5.12-linux-x86_64/arachni-1.5.1-0.5.12/system/gems/gems/activerecord-4.2.5.1/lib/active_record/inheritance.rb:61:in `new'
	from /home/gavin/Downloads/arachni-1.5.1-0.5.12-linux-x86_64/arachni-1.5.1-0.5.12/system/gems/gems/activerecord-4.2.5.1/lib/active_record/inheritance.rb:61:in `new'
	from /home/gavin/Downloads/arachni-1.5.1-0.5.12-linux-x86_64/arachni-1.5.1-0.5.12/system/gems/gems/activerecord-4.2.5.1/lib/active_record/persistence.rb:33:in `create'
	from /home/gavin/Downloads/arachni-1.5.1-0.5.12-linux-x86_64/arachni-1.5.1-0.5.12/bin/../system/arachni-ui-web/script/create_user:28:in `<main>'
```

Looks like something is wrong with how the hashing for how bcrypt works in ruby but I am not sure what the fix would be or whether this is related to issue above.

**Comment by RealOrko** [comment]
Hi

I just tried this on fedora 31 and noticed the default logins do not work. I tried: 

```
    Administrator:
        E-mail address: admin@admin.admin
        Password:       administrator

    User:
        E-mail address: user@user.user
        Password:       regular_user
```

Also when I try to run the `./arachni_web_create_user gavin@local.com password Gavin` I get the following error trace output: 

```
./arachni_web_create_user gavin@local.com password Gavin
/home/gavin/Downloads/arachni-1.5.1-0.5.12-linux-x86_64/arachni-1.5.1-0.5.12/system/gems/gems/bcrypt-3.1.11/lib/bcrypt/password.rb:60:in `initialize': invalid hash (BCrypt::Errors::InvalidHash)
	from /home/gavin/Downloads/arachni-1.5.1-0.5.12-linux-x86_64/arachni-1.5.1-0.5.12/system/gems/gems/bcrypt-3.1.11/lib/bcrypt/password.rb:46:in `new'
	from /home/gavin/Downloads/arachni-1.5.1-0.5.12-linux-x86_64/arachni-1.5.1-0.5.12/system/gems/gems/bcrypt-3.1.11/lib/bcrypt/password.rb:46:in `create'
	from /home/gavin/Downloads/arachni-1.5.1-0.5.12-linux-x86_64/arachni-1.5.1-0.5.12/system/gems/gems/devise-3.5.10/lib/devise/encryptor.rb:9:in `digest'
	from /home/gavin/Downloads/arachni-1.5.1-0.5.12-linux-x86_64/arachni-1.5.1-0.5.12/system/gems/gems/devise-3.5.10/lib/devise/models/database_authenticatable.rb:150:in `password_digest'
	from /home/gavin/Downloads/arachni-1.5.1-0.5.12-linux-x86_64/arachni-1.5.1-0.5.12/system/gems/gems/devise-3.5.10/lib/devise/models/database_authenticatable.rb:43:in `password='
	from /home/gavin/Downloads/arachni-1.5.1-0.5.12-linux-x86_64/arachni-1.5.1-0.5.12/system/gems/gems/activerecord-4.2.5.1/lib/active_record/attribute_assignment.rb:54:in `public_send'
	from /home/gavin/Downloads/arachni-1.5.1-0.5.12-linux-x86_64/arachni-1.5.1-0.5.12/system/gems/gems/activerecord-4.2.5.1/lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
	from /home/gavin/Downloads/arachni-1.5.1-0.5.12-linux-x86_64/arachni-1.5.1-0.5.12/system/gems/gems/activerecord-4.2.5.1/lib/active_record/attribute_assignment.rb:41:in `block in assign_attributes'
	from /home/gavin/Downloads/arachni-1.5.1-0.5.12-linux-x86_64/arachni-1.5.1-0.5.12/system/gems/gems/activerecord-4.2.5.1/lib/active_record/attribute_assignment.rb:35:in `each'
	from /home/gavin/Downloads/arachni-1.5.1-0.5.12-linux-x86_64/arachni-1.5.1-0.5.12/system/gems/gems/activerecord-4.2.5.1/lib/active_record/attribute_assignment.rb:35:in `assign_attributes'
	from /home/gavin/Downloads/arachni-1.5.1-0.5.12-linux-x86_64/arachni-1.5.1-0.5.12/system/gems/gems/activerecord-4.2.5.1/lib/active_record/core.rb:566:in `init_attributes'
	from /home/gavin/Downloads/arachni-1.5.1-0.5.12-linux-x86_64/arachni-1.5.1-0.5.12/system/gems/gems/activerecord-4.2.5.1/lib/active_record/core.rb:281:in `initialize'
	from /home/gavin/Downloads/arachni-1.5.1-0.5.12-linux-x86_64/arachni-1.5.1-0.5.12/system/gems/gems/activerecord-4.2.5.1/lib/active_record/inheritance.rb:61:in `new'
	from /home/gavin/Downloads/arachni-1.5.1-0.5.12-linux-x86_64/arachni-1.5.1-0.5.12/system/gems/gems/activerecord-4.2.5.1/lib/active_record/inheritance.rb:61:in `new'
	from /home/gavin/Downloads/arachni-1.5.1-0.5.12-linux-x86_64/arachni-1.5.1-0.5.12/system/gems/gems/activerecord-4.2.5.1/lib/active_record/persistence.rb:33:in `create'
	from /home/gavin/Downloads/arachni-1.5.1-0.5.12-linux-x86_64/arachni-1.5.1-0.5.12/bin/../system/arachni-ui-web/script/create_user:28:in `<main>'
```

Looks like something is wrong with how the hashing for how bcrypt works in ruby but I am not sure what the fix would be or whether this is related to issue above.

**Comment by RealOrko** [comment]
Here are some HTTP logs:

```
Puma 2.14.0 starting...
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://localhost:9292
::1 - - [07/Jan/2020:12:28:25 +0000] "GET /unauthenticated HTTP/1.1" 302 - 0.2508
::1 - - [07/Jan/2020:12:28:25 +0000] "GET /d/users/sign_in HTTP/1.1" 200 - 0.2797
::1 - - [07/Jan/2020:12:28:25 +0000] "GET %2Fassets%2Fapplication-0d44f400bffcbd209e9f88def75d6d40.css HTTP/1.1" 200 27419 0.0062
::1 - - [07/Jan/2020:12:28:25 +0000] "GET %2Fassets%2Fapplication-f3c1f7e259943a4701a6f8ec261e6340.js HTTP/1.1" 200 96297 0.0148
::1 - - [07/Jan/2020:12:28:26 +0000] "GET /404 HTTP/1.1" 404 728 0.0151
::1 - - [07/Jan/2020:12:29:11 +0000] "POST /500 HTTP/1.1" 500 643 0.2575
::1 - - [07/Jan/2020:12:29:11 +0000] "GET %2Ffavicon.ico HTTP/1.1" 200 - 0.0032
::1 - - [07/Jan/2020:12:29:16 +0000] "POST /500 HTTP/1.1" 500 643 0.1913
::1 - - [07/Jan/2020:12:29:16 +0000] "GET %2Ffavicon.ico HTTP/1.1" 200 - 0.0059
::1 - - [07/Jan/2020:12:29:30 +0000] "POST /500 HTTP/1.1" 500 643 0.2101
::1 - - [07/Jan/2020:12:30:38 +0000] "POST /500 HTTP/1.1" 500 643 0.1861
::1 - - [07/Jan/2020:12:34:22 +0000] "GET /unauthenticated HTTP/1.1" 302 - 0.0397
::1 - - [07/Jan/2020:12:34:22 +0000] "GET /d/users/sign_in HTTP/1.1" 200 - 0.0700
::1 - - [07/Jan/2020:12:34:34 +0000] "GET /d/users/sign_in HTTP/1.1" 200 - 0.0943
```
