### ISSUE TITLE
We're sorry, but something went wrong.

### ISSUE THREAD

**Issue by Known45** [Arachni/arachni-ui-web#76]
Hello,

It was working fine till yesterday but today it's throwing some error.

```
root@** ./arachni_web

Thin web server (v1.6.2 codename Doc Brown)
Maximum connections set to 1024
Listening on 0.0.0.0:9292, CTRL+C to stop
/root/Downloads/arachni-1.0.2-0.5.3/system/gems/gems/eventmachine-1.0.3/lib/eventmachine.rb:526:in `start_tcp_server': no acceptor (port is in use or requires root privileges) (RuntimeError)
    from /root/Downloads/arachni-1.0.2-0.5.3/system/gems/gems/eventmachine-1.0.3/lib/eventmachine.rb:526:in `start_server'
    from /root/Downloads/arachni-1.0.2-0.5.3/system/gems/gems/thin-1.6.2/lib/thin/backends/tcp_server.rb:16:in `connect'
    from /root/Downloads/arachni-1.0.2-0.5.3/system/gems/gems/thin-1.6.2/lib/thin/backends/base.rb:63:in `block in start'
    from /root/Downloads/arachni-1.0.2-0.5.3/system/gems/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `call'
    from /root/Downloads/arachni-1.0.2-0.5.3/system/gems/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
    from /root/Downloads/arachni-1.0.2-0.5.3/system/gems/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
    from /root/Downloads/arachni-1.0.2-0.5.3/system/gems/gems/thin-1.6.2/lib/thin/backends/base.rb:73:in `start'
    from /root/Downloads/arachni-1.0.2-0.5.3/system/gems/gems/thin-1.6.2/lib/thin/server.rb:162:in `start'
    from /root/Downloads/arachni-1.0.2-0.5.3/system/gems/gems/rack-1.5.2/lib/rack/handler/thin.rb:16:in `run'
    from /root/Downloads/arachni-1.0.2-0.5.3/system/gems/gems/rack-1.5.2/lib/rack/server.rb:264:in `start'
    from /root/Downloads/arachni-1.0.2-0.5.3/system/gems/gems/rack-1.5.2/lib/rack/server.rb:141:in `start'
    from /root/Downloads/arachni-1.0.2-0.5.3/system/gems/gems/rack-1.5.2/bin/rackup:4:in `<top (required)>'
    from /root/Downloads/arachni-1.0.2-0.5.3/bin/../system/gems/bin/rackup:23:in `load'
    from /root/Downloads/arachni-1.0.2-0.5.3/bin/../system/gems/bin/rackup:23:in `<main>'
```

Then when i try to access the WEB UI and login it shows "We're sorry, but something went wrong."

Thanks.

**Comment by HansulFathima** [comment]
![image](https://cloud.githubusercontent.com/assets/20277420/18505509/3447dd00-7a85-11e6-9c63-782551f0172b.png)

**Comment by HansulFathima** [comment]
@Zapotek May I know whats the issue. I am also getting the same error "We're sorry, but something went wrong."

**Comment by Zapotek** [comment]
@HansulFathima Can you please open a new issue and include the file: system/logs/webui/production.log

**Comment by basseput** [comment]
hallo saya adalah pengguna baru dalam tool arachni, disini saya mendapatkan masalah saat melakukan login pada arachni yaitu, "we sorry, but something went wrong" bisakah anda membantu saya?
<img width="960" alt="Screenshot 2023-09-08 021430" src="https://github.com/Arachni/arachni-ui-web/assets/144383841/283da3f9-6d3b-47d0-8d95-b020498698fb">
