### ISSUE TITLE
arachni_web_scan_import : TypeError: can't cast Regexp to text

### ISSUE THREAD

**Issue by calve** [Arachni/arachni-ui-web#80]
Hi.
First of all, thanks for your work on Arachni :) 

I am experiencing the following issue when trying to import a ``.afr`` report to the web ui :
```
$ bin/arachni_web_scan_import www.example.com\ 2015-01-05\ 13_55_25\ +0100.afr 1

#<TypeError: can't cast Regexp to text>
[
    [ 0] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/quoting.rb:81:in `type_cast'",
    [ 1] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/connection_adapters/sqlite3_adapter.rb:261:in `type_cast'",
    [ 2] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/connection_adapters/sqlite3_adapter.rb:295:in `block in exec_query'",
    [ 3] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/connection_adapters/sqlite3_adapter.rb:294:in `map'",
    [ 4] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/connection_adapters/sqlite3_adapter.rb:294:in `exec_query'",
    [ 5] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:68:in `exec_insert'",
    [ 6] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:95:in `insert'",
    [ 7] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'",
    [ 8] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/relation.rb:64:in `insert'",
    [ 9] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/persistence.rb:503:in `_create_record'",
    [10] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/attribute_methods/dirty.rb:87:in `_create_record'",
    [11] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/callbacks.rb:306:in `block in _create_record'",
    [12] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:113:in `call'",
    [13] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:113:in `call'",
    [14] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'",
    [15] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `call'",
    [16] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'",
    [17] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `call'",
    [18] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'",
    [19] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `call'",
    [20] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `run_callbacks'",
    [21] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/callbacks.rb:306:in `_create_record'",
    [22] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/timestamp.rb:57:in `_create_record'",
    [23] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/persistence.rb:483:in `create_or_update'",
    [24] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/callbacks.rb:302:in `block in create_or_update'",
    [25] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:113:in `call'",
    [26] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:113:in `call'",
    [27] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'",
    [28] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'",
    [29] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'",
    [30] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'",
    [31] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'",
    [32] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'",
    [33] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'",
    [34] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `call'",
    [35] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `run_callbacks'",
    [36] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/callbacks.rb:302:in `create_or_update'",
    [37] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/persistence.rb:103:in `save'",
    [38] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/validations.rb:51:in `save'",
    [39] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/attribute_methods/dirty.rb:21:in `save'",
    [40] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:268:in `block (2 levels) in save'",
    [41] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'",
    [42] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:199:in `transaction'",
    [43] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:208:in `transaction'",
    [44] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'",
    [45] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:268:in `block in save'",
    [46] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:283:in `rollback_active_record_state!'",
    [47] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:267:in `save'",
    [48] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/autosave_association.rb:423:in `save_belongs_to_association'",
    [49] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/autosave_association.rb:203:in `block in add_autosave_association_callbacks'",
    [50] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/autosave_association.rb:157:in `instance_eval'",
    [51] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/autosave_association.rb:157:in `block in define_non_cyclic_method'",
    [52] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:424:in `block in make_lambda'",
    [53] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:160:in `call'",
    [54] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:160:in `block in halting'",
    [55] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'",
    [56] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'",
    [57] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `call'",
    [58] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `run_callbacks'",
    [59] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/callbacks.rb:302:in `create_or_update'",
    [60] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/persistence.rb:103:in `save'",
    [61] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/validations.rb:51:in `save'",
    [62] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/attribute_methods/dirty.rb:21:in `save'",
    [63] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:268:in `block (2 levels) in save'",
    [64] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'",
    [65] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'",
    [66] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'",
    [67] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'",
    [68] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:208:in `transaction'",
    [69] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'",
    [70] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:268:in `block in save'",
    [71] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:283:in `rollback_active_record_state!'",
    [72] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:267:in `save'",
    [73] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/arachni-ui-web/app/models/scan.rb:651:in `create_report'",
    [74] "/home/goudale/Code/arachni-1.0.6-0.5.6/system/arachni-ui-web/app/models/scan.rb:634:in `import'",
    [75] "/home/goudale/Code/arachni-1.0.6-0.5.6/bin/../system/arachni-ui-web/script/scan_import:66:in `<main>'"
]
/home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/quoting.rb:81:in `type_cast': can't cast Regexp to text (TypeError)
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/connection_adapters/sqlite3_adapter.rb:261:in `type_cast'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/connection_adapters/sqlite3_adapter.rb:295:in `block in exec_query'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/connection_adapters/sqlite3_adapter.rb:294:in `map'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/connection_adapters/sqlite3_adapter.rb:294:in `exec_query'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:68:in `exec_insert'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:95:in `insert'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/relation.rb:64:in `insert'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/persistence.rb:503:in `_create_record'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/attribute_methods/dirty.rb:87:in `_create_record'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/callbacks.rb:306:in `block in _create_record'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:113:in `call'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:113:in `call'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `call'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `call'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `call'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `run_callbacks'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/callbacks.rb:306:in `_create_record'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/timestamp.rb:57:in `_create_record'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/persistence.rb:483:in `create_or_update'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/callbacks.rb:302:in `block in create_or_update'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:113:in `call'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:113:in `call'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `call'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `run_callbacks'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/callbacks.rb:302:in `create_or_update'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/persistence.rb:103:in `save'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/validations.rb:51:in `save'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/attribute_methods/dirty.rb:21:in `save'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:268:in `block (2 levels) in save'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:199:in `transaction'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:208:in `transaction'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:268:in `block in save'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:283:in `rollback_active_record_state!'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:267:in `save'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/autosave_association.rb:423:in `save_belongs_to_association'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/autosave_association.rb:203:in `block in add_autosave_association_callbacks'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/autosave_association.rb:157:in `instance_eval'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/autosave_association.rb:157:in `block in define_non_cyclic_method'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:424:in `block in make_lambda'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:160:in `call'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:160:in `block in halting'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `call'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `run_callbacks'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/callbacks.rb:302:in `create_or_update'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/persistence.rb:103:in `save'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/validations.rb:51:in `save'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/attribute_methods/dirty.rb:21:in `save'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:268:in `block (2 levels) in save'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:208:in `transaction'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:268:in `block in save'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:283:in `rollback_active_record_state!'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:267:in `save'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/system/arachni-ui-web/app/models/scan.rb:635:in `import'
        from /home/goudale/Code/arachni-1.0.6-0.5.6/bin/../system/arachni-ui-web/script/scan_import:66:in `<main>'
```

As expected, I have the exact same issue when importing from the web ui
The report was generate from the command line with this command : 
```
/bin/arachni http://www.example.com --plugin=autologin:url=http://www.example.com/portal2/login,parameters='email=plop@example.com&password=iloveyou',check='id_user' --scope-exclude-pattern "logout" --scope-extend-paths "paths.txt" --scope-auto-redundant --audit-links --audit-forms --audit-cookies --audit-headers
```

Any idea ? please let me know if you need extra informations

**Comment by Zapotek** [comment]
Thanks for letting me know, I've switched serializers for the report and testing it now. The current one was giving me too much trouble anyways.

Will keep you updated.

Cheers

**Comment by Zapotek** [comment]
All done, the fixed WebUI version will be released along Framework v1.1.

Thanks again.

**Comment by calve** [comment]
Waouh thank for the quick fix.
Do you think I can test to reimport my ``.afr`` in the upcoming nightly ?

**Comment by Zapotek** [comment]
No worries.
Unfortunately the v1.1 code is too unstable for the `experimental` (nightlies') branch so you won't be able get a package for it for a while.
