### ISSUE TITLE
The full report for this scan could not be retrieved due to an unknown error.

### ISSUE THREAD

**Issue by cclements** [Arachni/arachni-ui-web#81]
Ran a few scans with the latest nightly build today and received this message after scans complete:

The full report for this scan could not be retrieved due to an unknown error.

In the web_ui log after each scan finished, this error was reported:

42.42.4.14 - - [25/Jan/2015 16:44:43] "GET /scans/3.js?overview=false&amp;scan_id=3&amp;tab=all HTTP/1.1" 200 - 0.2879
42.42.4.14 - - [25/Jan/2015 16:44:43] "GET /navigation HTTP/1.1" 304 - 0.0234
I, [2015-01-25T16:44:46.195940 #17671]  INFO -- Call: service.native_progress [127.0.0.1]
I, [2015-01-25T16:44:46.437858 #17671]  INFO -- Call: service.native_abort_and_report [127.0.0.1]
#<ArgumentError: invalid byte sequence in UTF-8>
[
    [ 0] "/opt/arachni/system/gems/gems/psych-2.0.6/lib/psych/visitors/yaml_tree.rb:423:in `count'",
    [ 1] "/opt/arachni/system/gems/gems/psych-2.0.6/lib/psych/visitors/yaml_tree.rb:423:in `binary?'",
    [ 2] "/opt/arachni/system/gems/gems/psych-2.0.6/lib/psych/visitors/yaml_tree.rb:304:in `visit_String'",
    [ 3] "/opt/arachni/system/gems/gems/psych-2.0.6/lib/psych/visitors/yaml_tree.rb:150:in `accept'",
    [ 4] "/opt/arachni/system/gems/gems/psych-2.0.6/lib/psych/visitors/yaml_tree.rb:546:in `block in dump_ivars'",
    [ 5] "/opt/arachni/system/gems/gems/psych-2.0.6/lib/psych/visitors/yaml_tree.rb:544:in `each'",
    [ 6] "/opt/arachni/system/gems/gems/psych-2.0.6/lib/psych/visitors/yaml_tree.rb:544:in `dump_ivars'",
    [ 7] "/opt/arachni/system/gems/gems/psych-2.0.6/lib/psych/visitors/yaml_tree.rb:177:in `visit_Object'",
    [ 8] "/opt/arachni/system/gems/gems/psych-2.0.6/lib/psych/visitors/yaml_tree.rb:150:in `accept'",
    [ 9] "/opt/arachni/system/gems/gems/psych-2.0.6/lib/psych/visitors/yaml_tree.rb:546:in `block in dump_ivars'",
    [10] "/opt/arachni/system/gems/gems/psych-2.0.6/lib/psych/visitors/yaml_tree.rb:544:in `each'",
    [11] "/opt/arachni/system/gems/gems/psych-2.0.6/lib/psych/visitors/yaml_tree.rb:544:in `dump_ivars'",
    [12] "/opt/arachni/system/gems/gems/psych-2.0.6/lib/psych/visitors/yaml_tree.rb:177:in `visit_Object'",
    [13] "/opt/arachni/system/gems/gems/psych-2.0.6/lib/psych/visitors/yaml_tree.rb:150:in `accept'",
    [14] "/opt/arachni/system/gems/gems/psych-2.0.6/lib/psych/visitors/yaml_tree.rb:395:in `block in visit_Array'",
    [15] "/opt/arachni/system/gems/gems/psych-2.0.6/lib/psych/visitors/yaml_tree.rb:395:in `each'",
    [16] "/opt/arachni/system/gems/gems/psych-2.0.6/lib/psych/visitors/yaml_tree.rb:395:in `visit_Array'",
    [17] "/opt/arachni/system/gems/gems/psych-2.0.6/lib/psych/visitors/yaml_tree.rb:150:in `accept'",
    [18] "/opt/arachni/system/gems/gems/psych-2.0.6/lib/psych/visitors/yaml_tree.rb:546:in `block in dump_ivars'",
    [19] "/opt/arachni/system/gems/gems/psych-2.0.6/lib/psych/visitors/yaml_tree.rb:544:in `each'",
    [20] "/opt/arachni/system/gems/gems/psych-2.0.6/lib/psych/visitors/yaml_tree.rb:544:in `dump_ivars'",
    [21] "/opt/arachni/system/gems/gems/psych-2.0.6/lib/psych/visitors/yaml_tree.rb:177:in `visit_Object'",
    [22] "/opt/arachni/system/gems/gems/psych-2.0.6/lib/psych/visitors/yaml_tree.rb:150:in `accept'",
    [23] "/opt/arachni/system/gems/gems/psych-2.0.6/lib/psych/visitors/yaml_tree.rb:375:in `block in visit_Hash'",
    [24] "/opt/arachni/system/gems/gems/psych-2.0.6/lib/psych/visitors/yaml_tree.rb:373:in `each'",
    [25] "/opt/arachni/system/gems/gems/psych-2.0.6/lib/psych/visitors/yaml_tree.rb:373:in `visit_Hash'",
    [26] "/opt/arachni/system/gems/gems/psych-2.0.6/lib/psych/visitors/yaml_tree.rb:150:in `accept'",
    [27] "/opt/arachni/system/gems/gems/psych-2.0.6/lib/psych/visitors/yaml_tree.rb:546:in `block in dump_ivars'",
    [28] "/opt/arachni/system/gems/gems/psych-2.0.6/lib/psych/visitors/yaml_tree.rb:544:in `each'",
    [29] "/opt/arachni/system/gems/gems/psych-2.0.6/lib/psych/visitors/yaml_tree.rb:544:in `dump_ivars'",
    [30] "/opt/arachni/system/gems/gems/psych-2.0.6/lib/psych/visitors/yaml_tree.rb:177:in `visit_Object'",
    [31] "/opt/arachni/system/gems/gems/psych-2.0.6/lib/psych/visitors/yaml_tree.rb:150:in `accept'",
    [32] "/opt/arachni/system/gems/gems/psych-2.0.6/lib/psych/visitors/yaml_tree.rb:114:in `push'",
    [33] "/opt/arachni/system/gems/gems/psych-2.0.6/lib/psych.rb:409:in `dump'",
    [34] "/opt/arachni/system/gems/gems/activerecord-4.1.7/lib/active_record/coders/yaml_column.rb:20:in `dump'",
    [35] "/opt/arachni/system/gems/gems/activerecord-4.1.7/lib/active_record/attribute_methods/serialization.rb:110:in `serialize'",
    [36] "/opt/arachni/system/gems/gems/activerecord-4.1.7/lib/active_record/attribute_methods/serialization.rb:100:in `serialized_value'",
    [37] "/opt/arachni/system/gems/gems/activerecord-4.1.7/lib/active_record/attribute_methods/serialization.rb:186:in `typecasted_attribute_value'",
    [38] "/opt/arachni/system/gems/gems/activerecord-4.1.7/lib/active_record/attribute_methods.rb:436:in `block in arel_attributes_with_values'",
    [39] "/opt/arachni/system/gems/gems/activerecord-4.1.7/lib/active_record/attribute_methods.rb:435:in `each'",
    [40] "/opt/arachni/system/gems/gems/activerecord-4.1.7/lib/active_record/attribute_methods.rb:435:in `arel_attributes_with_values'",
    [41] "/opt/arachni/system/gems/gems/activerecord-4.1.7/lib/active_record/attribute_methods.rb:415:in `arel_attributes_with_values_for_create'",
    [42] "/opt/arachni/system/gems/gems/activerecord-4.1.7/lib/active_record/persistence.rb:501:in `_create_record'",
    [43] "/opt/arachni/system/gems/gems/activerecord-4.1.7/lib/active_record/attribute_methods/dirty.rb:87:in `_create_record'",
    [44] "/opt/arachni/system/gems/gems/activerecord-4.1.7/lib/active_record/callbacks.rb:306:in `block in _create_record'",
    [45] "/opt/arachni/system/gems/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:82:in `run_callbacks'",
    [46] "/opt/arachni/system/gems/gems/activerecord-4.1.7/lib/active_record/callbacks.rb:306:in `_create_record'",
    [47] "/opt/arachni/system/gems/gems/activerecord-4.1.7/lib/active_record/timestamp.rb:57:in `_create_record'",
    [48] "/opt/arachni/system/gems/gems/activerecord-4.1.7/lib/active_record/persistence.rb:483:in `create_or_update'",
    [49] "/opt/arachni/system/gems/gems/activerecord-4.1.7/lib/active_record/callbacks.rb:302:in `block in create_or_update'",
    [50] "/opt/arachni/system/gems/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:113:in `call'",
    [51] "/opt/arachni/system/gems/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:113:in `call'",
    [52] "/opt/arachni/system/gems/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:166:in `block in halting'",
    [53] "/opt/arachni/system/gems/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:86:in `call'",
    [54] "/opt/arachni/system/gems/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:86:in `run_callbacks'",
    [55] "/opt/arachni/system/gems/gems/activerecord-4.1.7/lib/active_record/callbacks.rb:302:in `create_or_update'",
    [56] "/opt/arachni/system/gems/gems/activerecord-4.1.7/lib/active_record/persistence.rb:103:in `save'",
    [57] "/opt/arachni/system/gems/gems/activerecord-4.1.7/lib/active_record/validations.rb:51:in `save'",
    [58] "/opt/arachni/system/gems/gems/activerecord-4.1.7/lib/active_record/attribute_methods/dirty.rb:21:in `save'",
    [59] "/opt/arachni/system/gems/gems/activerecord-4.1.7/lib/active_record/transactions.rb:268:in `block (2 levels) in save'",
    [60] "/opt/arachni/system/gems/gems/activerecord-4.1.7/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'",
    [61] "/opt/arachni/system/gems/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'",
    [62] "/opt/arachni/system/gems/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'",
    [63] "/opt/arachni/system/gems/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'",
    [64] "/opt/arachni/system/gems/gems/activerecord-4.1.7/lib/active_record/transactions.rb:208:in `transaction'",
    [65] "/opt/arachni/system/gems/gems/activerecord-4.1.7/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'",
    [66] "/opt/arachni/system/gems/gems/activerecord-4.1.7/lib/active_record/transactions.rb:268:in `block in save'",
    [67] "/opt/arachni/system/gems/gems/activerecord-4.1.7/lib/active_record/transactions.rb:283:in `rollback_active_record_state!'",
    [68] "/opt/arachni/system/gems/gems/activerecord-4.1.7/lib/active_record/transactions.rb:267:in `save'",
    [69] "/opt/arachni/system/gems/gems/activerecord-4.1.7/lib/active_record/persistence.rb:34:in `create'",
    [70] "/opt/arachni/system/arachni-ui-web/app/models/scan.rb:650:in `create_report'",
    [71] "/opt/arachni/system/arachni-ui-web/app/models/scan.rb:759:in `block in save_report_and_shutdown'",
    [72] "/opt/arachni/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/proxy.rb:58:in `call'",
    [73] "/opt/arachni/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/proxy.rb:58:in `block (2 levels) in translate'",
    [74] "/opt/arachni/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/client/handler.rb:77:in `call'",
    [75] "/opt/arachni/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/client/handler.rb:77:in `receive_response'",
    [76] "/opt/arachni/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/client/handler.rb:137:in `receive_object'",
    [77] "/opt/arachni/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/protocol.rb:52:in `on_read'",
    [78] "/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/connection.rb:236:in `block in _read'",
    [79] "/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/connection/error.rb:26:in `call'",
    [80] "/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/connection/error.rb:26:in `translate'",
    [81] "/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/connection.rb:235:in `_read'",
    [82] "/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:568:in `each'",
    [83] "/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:568:in `block in process_connections'",
    [84] "/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:568:in `each'",
    [85] "/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:568:in `process_connections'",
    [86] "/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:317:in `block in run'",
    [87] "/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:308:in `loop'",
    [88] "/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:308:in `run'",
    [89] "/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:350:in `block in run_in_thread'"
]
I, [2015-01-25T16:44:46.958783 #17671]  INFO -- Call: service.shutdown [127.0.0.1]
I, [2015-01-25T16:44:47.382510 #17671]  INFO -- System: Shutting down in 2 seconds...

**Comment by Zapotek** [comment]
Thanks for letting me know, although this issue has been resolved in the [Framework v1.1](https://github.com/Arachni/arachni/tree/v1.1) [integration branch](https://github.com/Arachni/arachni-ui-web/tree/framework-v1.1).
