### ISSUE TITLE
Script crashed

### ISSUE THREAD

**Issue by Cleveridge** [Arachni/arachni-ui-web#83]
While running Arachni_web a script crashed and forced me to reboot my computer.
After the reboot the scan showed the following errors:
```
Connection refused - SSL_connect for '127.0.0.1:33646'.
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/connection/tls.rb:66:in `connect_nonblock'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/connection/tls.rb:66:in `start_tls'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/protocol.rb:23:in `on_connect'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/connection.rb:274:in `configure'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:205:in `block in connect'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/connection/error.rb:26:in `call'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/connection/error.rb:26:in `translate'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:200:in `connect'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/client.rb:111:in `connect'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/client.rb:216:in `call_async'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/client.rb:196:in `call'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/proxy.rb:73:in `forward'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/proxy.rb:57:in `block in translate'
/root/Downloads/arachni-1.0.6-0.5.6/system/arachni-ui-web/app/models/scan.rb:519:in `refresh'
/root/Downloads/arachni-1.0.6-0.5.6/system/arachni-ui-web/lib/scan_manager.rb:152:in `block in refresh'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/iterator.rb:129:in `call'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/iterator.rb:129:in `block in each'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/iterator.rb:241:in `call'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/iterator.rb:241:in `block in spawn_workers'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/tasks/base.rb:52:in `call'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/tasks/base.rb:52:in `call_task'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/tasks/one_off.rb:23:in `call'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/tasks.rb:96:in `block in call'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/tasks.rb:96:in `each'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/tasks.rb:96:in `call'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:310:in `block in run'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:308:in `loop'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:308:in `run'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:350:in `block in run_in_thread'
--------------------------------------------------------------------------------
/root/Downloads/arachni-1.0.6-0.5.6/system/arachni-ui-web/app/models/scan.rb:528:in `block in refresh'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/proxy.rb:58:in `call'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/proxy.rb:58:in `block (2 levels) in translate'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/client.rb:209:in `call'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/client.rb:209:in `set_exception'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/client.rb:218:in `block in call_async'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/client.rb:111:in `call'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/client.rb:111:in `connect'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/client.rb:216:in `call_async'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/client.rb:196:in `call'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/proxy.rb:73:in `forward'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/proxy.rb:57:in `block in translate'
/root/Downloads/arachni-1.0.6-0.5.6/system/arachni-ui-web/app/models/scan.rb:519:in `refresh'
/root/Downloads/arachni-1.0.6-0.5.6/system/arachni-ui-web/lib/scan_manager.rb:152:in `block in refresh'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/iterator.rb:129:in `call'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/iterator.rb:129:in `block in each'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/iterator.rb:241:in `call'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/iterator.rb:241:in `block in spawn_workers'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/tasks/base.rb:52:in `call'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/tasks/base.rb:52:in `call_task'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/tasks/one_off.rb:23:in `call'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/tasks.rb:96:in `block in call'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/tasks.rb:96:in `each'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/tasks.rb:96:in `call'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:310:in `block in run'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:308:in `loop'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:308:in `run'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:350:in `block in run_in_thread'
********************************************************************************
```
I was running a scan against an up to date wordpress website and I had the same issue with another wordpress website yesterday

The gui said it was scanning a css page of a template and after I while I got the pop up a script in
```
assets/application-c587a62573c1a152991bc30f01da0ce7.js:3
```
crashed.

**Comment by Zapotek** [comment]
The first error is simply because you restarted your machine, the scan process was killed and the WebUI couldn't connect to it.

As for the second error, looks like a JS bug in the the interface. How come you were forced to reboot because of that?

**Comment by Cleveridge** [comment]
The reboot was necessary because my browser (firefox in Kali) showed the pop up of the script issue to late. The script already used to much of my resources. The moment I wanted to click the button to stop the script my screen was frozen.

**Comment by Zapotek** [comment]
Hm, what amounts of resources were available?

**Comment by Cleveridge** [comment]
4GB RAM.
Intel Core2 Duo CPU T6600 @ 2.2GHz x 2
64 bit

To lower the pressure on the websites I have set 'HTTP request concurrency limit' just on 2.

But I believe the resources problem is caused by a script issue.

I disabled some passive checks and it seems the issue doesn't show up.
At this moment I have disabled :
- captcha
- common_directories
- common_files
- credit_card
- cvs_cvn_users
- directory_listing
- emails
- ssn

The following days I will try to eliminate the check that causes the issue

**Comment by Zapotek** [comment]
Do you happen to have enabled the issue charts in the scan progress page?

**Comment by Cleveridge** [comment]
Yes, the charts are enabled

**Comment by Cleveridge** [comment]
I did a scan of the same wordpress website with the issue charts disabled and it didn't crash.

**Comment by Zapotek** [comment]
Yeah I figured as much, the charting lib seems to have a leak. I'll see if I can fix it or replace it altogether.
Thanks for the feedback man. :)

**Comment by Zapotek** [comment]
Unfortunately I couldn't make it work so I had to remove charting.
I do appreciate the feedback man, cheers.

**Comment by Cleveridge** [comment]
Maybe, just call the charts when the scan has finished...

**Comment by Zapotek** [comment]
The page will still refresh to reflect reviewed issues and comments so you'd end up with a leak again.

**Comment by Cleveridge** [comment]
Ah, Ok... I leave it in your good hands ;-)
You're doing a great job with Arachni.
