### ISSUE TITLE
The full report for this scan could not be retrieved due to an unknown error. 

### ISSUE THREAD

**Issue by nitzanm** [Arachni/arachni-ui-web#90]
I am trying to run a scan, which completes successfully, but the top of the report shows "The full report for this scan could not be retrieved due to an unknown error." and I cannot export the scan results.  The system/logs/webui/production.log shows the following message:

```
ArgumentError: string contains null byte: INSERT INTO "reports" ("created_at", "object", "scan_id", "sitemap", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"
string contains null byte
.../system/gems/gems/activerecord-4.1.7/lib/active_record/connection_adapters/postgresql_adapter.rb:832:in `send_query_prepared'
.../system/gems/gems/activerecord-4.1.7/lib/active_record/connection_adapters/postgresql_adapter.rb:832:in `block in exec_cache'
.../system/gems/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract_adapter.rb:373:in `block in log'
.../system/gems/gems/activesupport-4.1.7/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
.../system/gems/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract_adapter.rb:367:in `log'
.../system/gems/gems/activerecord-4.1.7/lib/active_record/connection_adapters/postgresql_adapter.rb:831:in `exec_cache'
.../system/gems/gems/activerecord-4.1.7/lib/active_record/connection_adapters/postgresql/database_statements.rb:138:in `exec_query'
.../system/gems/gems/activerecord-4.1.7/lib/active_record/connection_adapters/postgresql/database_statements.rb:177:in `exec_insert'
.../system/gems/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/database_statements.rb:95:in `insert'
.../system/gems/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
.../system/gems/gems/activerecord-4.1.7/lib/active_record/relation.rb:64:in `insert'
.../system/gems/gems/activerecord-4.1.7/lib/active_record/persistence.rb:503:in `_create_record'
.../system/gems/gems/activerecord-4.1.7/lib/active_record/attribute_methods/dirty.rb:87:in `_create_record'
.../system/gems/gems/activerecord-4.1.7/lib/active_record/callbacks.rb:306:in `block in _create_record'
.../system/gems/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:82:in `run_callbacks'
.../system/gems/gems/activerecord-4.1.7/lib/active_record/callbacks.rb:306:in `_create_record'
.../system/gems/gems/activerecord-4.1.7/lib/active_record/timestamp.rb:57:in `_create_record'
.../system/gems/gems/activerecord-4.1.7/lib/active_record/persistence.rb:483:in `create_or_update'
.../system/gems/gems/activerecord-4.1.7/lib/active_record/callbacks.rb:302:in `block in create_or_update'
.../system/gems/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:113:in `call'
.../system/gems/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:113:in `call'
.../system/gems/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:166:in `block in halting'
.../system/gems/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:86:in `call'
.../system/gems/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:86:in `run_callbacks'
.../system/gems/gems/activerecord-4.1.7/lib/active_record/callbacks.rb:302:in `create_or_update'
.../system/gems/gems/activerecord-4.1.7/lib/active_record/persistence.rb:103:in `save'
.../system/gems/gems/activerecord-4.1.7/lib/active_record/validations.rb:51:in `save'
.../system/gems/gems/activerecord-4.1.7/lib/active_record/attribute_methods/dirty.rb:21:in `save'
.../system/gems/gems/activerecord-4.1.7/lib/active_record/transactions.rb:268:in `block (2 levels) in save'
.../system/gems/gems/activerecord-4.1.7/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
.../system/gems/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
.../system/gems/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
.../system/gems/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
.../system/gems/gems/activerecord-4.1.7/lib/active_record/transactions.rb:208:in `transaction'
.../system/gems/gems/activerecord-4.1.7/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
.../system/gems/gems/activerecord-4.1.7/lib/active_record/transactions.rb:268:in `block in save'
.../system/gems/gems/activerecord-4.1.7/lib/active_record/transactions.rb:283:in `rollback_active_record_state!'
.../system/gems/gems/activerecord-4.1.7/lib/active_record/transactions.rb:267:in `save'
.../system/gems/gems/activerecord-4.1.7/lib/active_record/persistence.rb:34:in `create'
.../system/arachni-ui-web/app/models/scan.rb:650:in `create_report'
.../system/arachni-ui-web/app/models/scan.rb:759:in `block in save_report_and_shutdown'
.../system/gems/gems/arachni-rpc-0.2.1.2/lib/arachni/rpc/proxy.rb:58:in `call'
.../system/gems/gems/arachni-rpc-0.2.1.2/lib/arachni/rpc/proxy.rb:58:in `block (2 levels) in translate'
.../system/gems/gems/arachni-rpc-0.2.1.2/lib/arachni/rpc/client/handler.rb:77:in `call'
.../system/gems/gems/arachni-rpc-0.2.1.2/lib/arachni/rpc/client/handler.rb:77:in `receive_response'
.../system/gems/gems/arachni-rpc-0.2.1.2/lib/arachni/rpc/client/handler.rb:137:in `receive_object'
.../system/gems/gems/arachni-rpc-0.2.1.2/lib/arachni/rpc/protocol.rb:52:in `on_read'
.../system/gems/gems/arachni-reactor-0.1.0/lib/arachni/reactor/connection.rb:255:in `block in _read'
.../system/gems/gems/arachni-reactor-0.1.0/lib/arachni/reactor/connection/error.rb:26:in `call'
.../system/gems/gems/arachni-reactor-0.1.0/lib/arachni/reactor/connection/error.rb:26:in `translate'
.../system/gems/gems/arachni-reactor-0.1.0/lib/arachni/reactor/connection.rb:254:in `_read'
.../system/gems/gems/arachni-reactor-0.1.0/lib/arachni/reactor/connection/tls.rb:115:in `_read'
.../system/gems/gems/arachni-reactor-0.1.0/lib/arachni/reactor.rb:574:in `each'
.../system/gems/gems/arachni-reactor-0.1.0/lib/arachni/reactor.rb:574:in `block in process_connections'
.../system/gems/gems/arachni-reactor-0.1.0/lib/arachni/reactor.rb:574:in `each'
.../system/gems/gems/arachni-reactor-0.1.0/lib/arachni/reactor.rb:574:in `process_connections'
.../system/gems/gems/arachni-reactor-0.1.0/lib/arachni/reactor.rb:316:in `block in run'
.../system/gems/gems/arachni-reactor-0.1.0/lib/arachni/reactor.rb:307:in `loop'
.../system/gems/gems/arachni-reactor-0.1.0/lib/arachni/reactor.rb:307:in `run'
.../system/gems/gems/arachni-reactor-0.1.0/lib/arachni/reactor.rb:349:in `block in run_in_thread'
```

**Comment by Zapotek** [comment]
Hello,

Could you please retry using the [nightlies](http://downloads.arachni-scanner.com/nightlies/)?
The report serialization format has changed to fix those types of errors.

Cheers
